### ISSUE TITLE
Is the project must be build with Scala2.10.5 and spark1.5.1?

### ISSUE THREAD

**Issue by huangjiahong0601** [peoplehum/BagOfWords_SentimentAnalysis_Template#5]
I encounter an erro when building the project:

[INFO] [Console$] [error] /Users/jia/IdeaProjects/pio/bagOfWordsSentimentAnalysis/src/main/scala/com/coviam/sentimentAnalysis/engine/Evaluation.scala:6: case classes without a parameter list are not allowed;
[INFO] [Console$] [error] use either case objects or case classes with an explicit `()' as a parameter list.
[INFO] [Console$] [error] case class Accuracy extends AverageMetric[EmptyEvaluationInfo, Query, PredictedResult, ActualResult]{
[INFO] [Console$] [error]                    ^
[INFO] [Console$] [error] one error found
[INFO] [Console$] [error] (compile:compileIncremental) Compilation failed
[INFO] [Console$] [error] Total time: 69 s, completed 2017-5-5 10:24:23
[ERROR] [Console$] Return code of previous step is 1. Aborting.

And my build.sbt change to(my machine scala is 2.11.6 and spark is 2.1.0,predictionio is 0.10.0)：

assemblySettings

name := "SantimentAnalysis_BagOfWords_Model"

version := "1.0"

scalaVersion := "2.11.6"

libraryDependencies ++= Seq(
  "org.apache.predictionio"    %% "apache-predictionio-core"          % "0.11.0-incubating" % "provided",
  "org.apache.spark" %% "spark-core"    % "2.1.0" % "provided",
  "org.apache.spark" %% "spark-mllib"   % "2.1.0" % "provided"
  )

**Comment by bansarishah** [comment]
Yes, it is required to build this template using scala-2.10.6 and spark 1.5.1 else it may throw an error of NoSuchMethod Found because of version mismatch. In case to use scala 2.11.6 and spark - 2.1.0, some source code changes may require.
